jobs:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode11.2
      env:
        - LC_CTYPE=en_US.UTF-8
        - LANG=en_US.UTF-8
        - IOS_VER=13.2.2
        - IOS_SDK=iphonesimulator13.2
        - SIMULATOR_NAME="iPhone 8"

      cache:
        directories:
          - $HOME/Carthage

      script:
        - set -o pipefail
        - carthage version
        - carthage update --platform iOS
        - cd ios
        - xcodebuild -version
        - xcodebuild -showsdks
        - instruments -s devices
        - xcodebuild -scheme "RIBs" -destination "OS=$IOS_VER,name=$SIMULATOR_NAME" -sdk "$IOS_SDK" -configuration Release clean build | xcpretty -c;
        - xcodebuild -scheme "RIBs" -destination "OS=$IOS_VER,platform=iOS Simulator,name=$SIMULATOR_NAME" -sdk "$IOS_SDK" -configuration Debug clean build test | xcpretty -c;

branches:
  except:
    - gh-pages
    - assets

notifications:
  email: false
